
production:
  solr:
    hostname: index.websolr.com
    port: 80
    log_level: WARNING
    path: /solr/8c7cb9dda71
    # read_timeout: 2
    # open_timeout: 0.5
development:
  solr:
    hostname: index.websolr.com
    port: 80
    log_level: INFO
    path: /solr/8c7cb9dda71
test:
  solr:
    hostname: index.websolr.com
    port: 80
    log_level: WARNING
    path: /solr/8c7cb9dda71